version: '3'

services:
  #web:
  #  container_name: web
  #  image: nginx
  #  build: 
  #    context: ./web
  #    dockerfile: Dockerfile
  #  #depends_on:
  #  # - lcd
  #  ports:
  #    - "8080:8080"
  #  volumes:
  #    - ./web/conf.d:/etc/nginx/conf.d
  #    - ./web/src:/usr/share/nginx/html
  #  networks:
  #    - backend_network
  
  lcd:
    container_name: lcd
    tty: true
    image: lcd_image
    build: 
      context: .
      dockerfile: ./lcd/lcd-app/Dockerfile
      args:
        - NODE_ENV
    volumes:
      - ./lcd/lcd-app:/var/www
      - /var/www/app/.next
      - /var/www/app/node_modules
    command: >
      /bin/sh -c "if [ '$$NODE_ENV' = 'prod' ]; then
               npm run build && npm start;
             else
               npm run dev;
             fi"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - WATCHPACK_POLLING=true

networks:
  backend_network:
    driver: bridge
